### ISSUE TITLE
Wrong URL in Curl example for "Create a New Key"

### ISSUE THREAD

**Issue by araujof** [IBM-Bluemix-Docs/key-protect#2]
The URL in the Curl example for "Create a New Key"  is wrong (see below):

```
curl -X POST \
  https://<region>.kms.cloud.ibm.com/api/v2 \
  -H 'authorization: Bearer <IAM_token>' \
  -H 'bluemix-instance: <instance_ID>' \
  -H 'content-type: application/vnd.ibm.kms.key+json' \
  -d '{
    "metadata": {
      "collectionType": "application/vnd.ibm.kms.key+json",
      "collectionTotal": 1
    },
    "resources": [
    {
      "type": "application/vnd.ibm.kms.key+json",
      "name": "Root-key",
      "description": "...",
      "extractable": false
      }
    ]
  }'
```
It should be:
```
https://<region>.kms.cloud.ibm.com/api/v2/keys
```

**Comment by ccbarragan** [comment]
Hi, thank you for opening this issue!

We've fixed the problem here: https://cloud.ibm.com/apidocs/key-protect#create-a-new-key

![Screen Shot 2019-03-14 at 3 31 35 PM](https://user-images.githubusercontent.com/28902259/54389546-52bd5f00-466e-11e9-9699-387b821af883.png)


Feel free to report back if you encounter any other issues. Thanks again!
